import type React from "react"
import type { Metadata } from "next"
import { Bricolage_Grotesque, Playfair_Display } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import { Suspense } from "react"

import { PostHogProvider } from "@/components/posthog-provider"
import "./globals.css"
import "./guildy-styles.css"
import "./guildy-sections.css"

// Self-hosted via next/font so there is no render-blocking external request.
// The design's --font-display / --font-serif point at these variables.
const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
  variable: "--font-bricolage",
  display: "swap",
})

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["500", "600"],
  style: ["normal", "italic"],
  variable: "--font-playfair",
  display: "swap",
})

// www is the canonical host (apex guildy.ai 308s to www). metadataBase,
// canonical, og:url, sitemap, robots, and JSON-LD all use www so the
// canonical never points at a redirect.
const siteUrl = "https://www.guildy.ai"
const title = "Guildy: Walk in ready"
const description =
  "Free AI interview prep from the real job description, your resume, and the exact round. Quick Prep in about 20 seconds, no signup. Then track every application and round in one command center."

// Organization + SoftwareApplication structured data. Quick Prep is free,
// Deep Prep is $19.99/mo. No aggregateRating: there are no real reviews.
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${siteUrl}/#organization`,
      name: "Guildy",
      url: siteUrl,
      logo: `${siteUrl}/images/logo-plum.png`,
      sameAs: [
        "https://x.com/tryguildy",
        "https://bsky.app/profile/tryguildy.bsky.social",
      ],
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${siteUrl}/#software`,
      name: "Guildy",
      url: siteUrl,
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      description,
      publisher: { "@id": `${siteUrl}/#organization` },
      offers: [
        {
          "@type": "Offer",
          name: "Quick Prep",
          price: "0",
          priceCurrency: "USD",
          description: "Free AI interview prep, no signup required.",
        },
        {
          "@type": "Offer",
          name: "Deep Prep (monthly)",
          price: "19.99",
          priceCurrency: "USD",
          category: "subscription",
          description: "Round-by-round prep with model answers and a story bank.",
        },
      ],
    },
  ],
}

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title,
  description,
  applicationName: "Guildy",
  keywords: [
    "interview prep",
    "AI interview prep",
    "job pipeline",
    "job tracker",
    "hiring manager interview",
    "full loop interview",
    "stage-specific prep",
  ],
  openGraph: {
    type: "website",
    url: siteUrl,
    siteName: "Guildy",
    title,
    description,
    // og:image is generated by app/opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    // twitter:image is generated by app/twitter-image.tsx.
  },
  alternates: {
    canonical: "/",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${bricolage.variable} ${playfair.variable}`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <Suspense fallback={null}>
          <PostHogProvider>{children}</PostHogProvider>
        </Suspense>
        <Analytics />
      </body>
    </html>
  )
}
