import type { Metadata } from "next"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms of Service · Guildy",
  description: "The terms that govern your use of Guildy.",
  alternates: { canonical: "/terms" },
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-[720px] px-6 py-16 lg:px-8">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Link>

        <article className="text-foreground leading-[1.7]">
          <h1 className="font-serif text-4xl font-bold tracking-tight text-foreground mb-3">
            Terms of Service
          </h1>
          <p className="text-muted-foreground mb-8">Effective Date: May 8, 2026</p>

          <div className="space-y-1 mb-10">
            <p>
              <strong>Company Name:</strong> Guildy.ai, Inc.
            </p>
            <p>
              <strong>Product/App:</strong> Guildy.ai
            </p>
            <p>
              <strong>Website:</strong>{" "}
              <a href="https://guildy.ai" className="text-accent hover:underline">
                https://guildy.ai
              </a>
            </p>
            <p>
              <strong>Contact Email:</strong>{" "}
              <a href="mailto:support@guildy.ai" className="text-accent hover:underline">
                support@guildy.ai
              </a>
            </p>
            <p>
              <strong>Business Address:</strong> Guildy.ai, Inc., San Francisco, CA, USA
            </p>
          </div>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">1. Agreement to Terms</h2>
            <p>
              By accessing or using Guildy (the "Service") you ("you," "your," "User") agree to be
              bound by these Terms of Service (the "TOS"), our Privacy Policy and any other policies
              referenced herein. If you do not agree to these TOS, you may not access or use the
              Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">2. Changes to Terms</h2>
            <p>
              We may revise these TOS at any time. When we do, we will post the revised version on
              our website with a new "Effective Date." Continued use of the Service after such
              changes constitutes your acceptance of the revised TOS.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              3. Description of Service
            </h2>
            <p>
              Guildy is a job pipeline tracker with AI-driven interview preparation. Users manually
              add jobs, paste job descriptions and interview context, and receive stage-specific
              preparation generated by large language models. The Service is made available through
              a web-based interface and other channels we may offer.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              4. User Accounts &amp; Access
            </h2>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">4.1 Account Registration</h3>
            <p>
              You must provide accurate, complete information when registering. You are responsible
              for maintaining the confidentiality of any login credentials and for all activity
              under your account.
            </p>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">4.2 Permissions &amp; Use</h3>
            <p>
              You may use the Service only in compliance with these TOS, and all applicable laws
              and regulations. You may not access the Service in a way that harms, impairs or
              overloads it, or attempt to reverse engineer or modify any part of the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              5. License Grant &amp; Intellectual Property
            </h2>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">5.1 License Grant</h3>
            <p>
              Guildy.ai, Inc. grants you a limited, non-exclusive, non-transferable, revocable
              license to access and use the Service in accordance with these TOS. All rights not
              expressly granted are reserved by the Company.
            </p>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">5.2 Ownership</h3>
            <p>
              The Service, software, content, databases, and underlying technology, including all
              associated intellectual property rights, are and remain the property of Guildy.ai,
              Inc. or its licensors. You retain ownership of your data, as further described in the
              Privacy Policy, subject to the rights granted to us to provide the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              6. Payment &amp; Subscription
            </h2>
            <p>
              The Service offers free and paid features. Free tier includes basic pipeline tracking
              and Quick Prep generation. Paid tier ("Deep Prep") is available via monthly
              subscription. Fees, billing cycles, payment terms, upgrades, downgrades, and refunds
              are described on the pricing page or in applicable supplemental agreements. You are
              responsible for providing valid payment information and for the timely payment of all
              fees. Failure to pay on time may result in suspension or termination of access to the
              paid features. Payments are processed by Stripe. You agree to Stripe's Terms of
              Service and Privacy Policy as part of your subscription.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              7. Termination &amp; Suspension
            </h2>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">7.1 Termination by You</h3>
            <p>
              You may delete your account at any time via the Service (Settings → Delete Account)
              or by contacting support@guildy.ai. Deletion will trigger removal of your account
              data as described in our Privacy Policy.
            </p>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">
              7.2 Termination by Company
            </h3>
            <p>
              We may suspend or terminate your access to the Service at our discretion, including
              for violation of these TOS, non-payment, or abuse of the Service. Upon termination,
              your right to access the Service ceases, and we may delete or archive your data in
              accordance with our data retention policies.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              8. Disclaimers &amp; Limitations of Liability
            </h2>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">
              8.1 Disclaimer of Warranties
            </h3>
            <p>
              The Service is provided "AS IS" and "AS AVAILABLE." Guildy.ai, Inc. disclaims all
              warranties and conditions of any kind, whether express or implied, including but not
              limited to merchantability, fitness for a particular purpose, or non-infringement.
              Interview preparation generated by Guildy is informational only and is not a
              guarantee of interview outcomes, employment, or any specific result.
            </p>

            <h3 className="font-serif text-xl font-semibold mt-6 mb-3">
              8.2 Limitation of Liability
            </h3>
            <p>
              To the fullest extent permitted by law, Guildy.ai, Inc.'s total liability for any
              claim arising out of or related to these TOS or the Service is limited to the amount
              you paid, if any, during the twelve (12) months preceding the claim. In no event
              shall Guildy.ai, Inc. be liable for any indirect, incidental, special, consequential
              or punitive damages, including lost profits, data loss or business interruption, even
              if advised of the possibility of such damages.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Guildy.ai, Inc., its affiliates, officers,
              directors, employees and agents from and against any and all claims, liabilities,
              damages, losses, costs or expenses (including attorneys' fees) arising out of or
              related to your use of the Service, your breach of these TOS, or your violation of
              any law or right of a third-party.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">10. Privacy Policy</h2>
            <p>
              Your use of the Service is also governed by our Privacy Policy. By using the Service,
              you consent to our collection, use and storage of your information as described in
              the Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              11. International Use &amp; Export Controls
            </h2>
            <p>
              The Service is offered from the United States and serves users globally. You agree to
              comply with all laws and regulations of your jurisdiction. Use of the Service is
              subject to U.S. export control laws and other applicable restrictions.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              12. Data Protection &amp; Security
            </h2>
            <p>
              We use commercially reasonable measures to protect your data, as described in the
              Privacy Policy. However, no system can guarantee absolute security, and we cannot
              guarantee it.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              13. Governing Law &amp; Dispute Resolution
            </h2>
            <p>
              These TOS are governed by the laws of the State of California, USA, without regard to
              its conflict-of-law provisions. Any dispute arising from or relating to these TOS or
              the Service will be resolved in the state or federal courts located in San Francisco
              County, California. You and Guildy.ai, Inc. consent to the personal jurisdiction of
              those courts.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              14. Modifications to the Service
            </h2>
            <p>
              We may modify, suspend or discontinue the Service (or any part thereof) at any time
              with or without notice. We will use commercially reasonable efforts to provide notice
              of material changes, but we are not obligated to do so.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">
              15. Acceptable Use &amp; Prohibited Conduct
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>Use the Service for any fraudulent, unlawful or abusive activity.</li>
              <li>Attempt to gain unauthorized access to the Service or any related network.</li>
              <li>
                Use the Service in a manner that would interfere with others' use of it or impair
                the integrity or security of the Service.
              </li>
              <li>
                Submit content that is unlawful, defamatory, harassing, or that violates the rights
                of third parties.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">16. Feedback</h2>
            <p>
              If you provide any suggestions, comments or other feedback relating to the Service
              ("Feedback"), you assign all rights in such Feedback to Guildy.ai, Inc. We shall be
              free to use, disclose, modify and incorporate the Feedback without restriction.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">17. Severability</h2>
            <p>
              If any provision of these TOS is held invalid or unenforceable, the remaining
              provisions will remain in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">18. Waiver</h2>
            <p>
              No waiver of any term of these TOS shall be deemed a further or continuing waiver of
              such term or any other term.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">19. Entire Agreement</h2>
            <p>
              These TOS, together with the Privacy Policy and any other documents expressly
              referenced, constitute the entire agreement between you and Guildy.ai, Inc. regarding
              the Service and supersede any prior or contemporaneous agreements.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-semibold mt-10 mb-4">20. Contact Us</h2>
            <p>
              Guildy.ai, Inc.
              <br />
              San Francisco, CA, USA
              <br />
              <a href="mailto:support@guildy.ai" className="text-accent hover:underline">
                support@guildy.ai
              </a>
            </p>
          </section>
        </article>
      </div>
    </div>
  )
}
